import { Router } from 'express';
import { healthRouter } from './health.routes';
import { authRouter } from './auth.routes';
import { propertyRouter } from './properties.routes';
import { reservationRouter } from './reservation.routes';
import { guestRouter } from './guest.routes';
import { calendarRouter } from './calendar.routes';
import { cleaningRouter } from './cleaning.routes';
import { maintenanceRouter } from './maintenance.routes';
import { inventoryRouter } from './inventory.routes';
import { reportRouter } from './report.routes';
import { aiRouter } from './ai.routes';
import { integrationRouter } from './integration.routes';
import { notificationRouter } from './notification.routes';
import { settingsRouter } from './settings.routes';

export const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/properties', propertyRouter);
router.use('/reservations', reservationRouter);
router.use('/guests', guestRouter);
router.use('/calendar', calendarRouter);
router.use('/cleaning', cleaningRouter);
router.use('/maintenance', maintenanceRouter);
router.use('/inventory', inventoryRouter);
router.use('/reports', reportRouter);
router.use('/ai', aiRouter);
router.use('/integrations', integrationRouter);
router.use('/notifications', notificationRouter);
router.use('/settings', settingsRouter);
